// Code generated by go-bindata. DO NOT EDIT.
// sources:
// static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css
// static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css.map
// static/dist/index.html
// static/fonts/element-icons.6f0a763.ttf
// static/imgs/avatar.jpg
// static/imgs/fav.ico
// static/js/app.f12927113878f5ed9a9c.js
// static/js/app.f12927113878f5ed9a9c.js.map
// static/js/flexible.js
// static/js/manifest.2ae2e69a05c33dfc65f8.js
// static/js/manifest.2ae2e69a05c33dfc65f8.js.map
// static/js/test.js
// static/js/vendor.ce16a214c4761af53a7d.js
// static/js/vendor.ce16a214c4761af53a7d.js.map

package asset

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcss reads file data from disk. It returns an error on failure.
func bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcss() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css"
	name := "static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcssmap reads file data from disk. It returns an error on failure.
func bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcssmap() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css.map"
	name := "static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticDistIndexhtml reads file data from disk. It returns an error on failure.
func bindataStaticDistIndexhtml() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/dist/index.html"
	name := "static/dist/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticFontsElementicons6f0a763ttf reads file data from disk. It returns an error on failure.
func bindataStaticFontsElementicons6f0a763ttf() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/fonts/element-icons.6f0a763.ttf"
	name := "static/fonts/element-icons.6f0a763.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticImgsAvatarjpg reads file data from disk. It returns an error on failure.
func bindataStaticImgsAvatarjpg() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/imgs/avatar.jpg"
	name := "static/imgs/avatar.jpg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticImgsFavico reads file data from disk. It returns an error on failure.
func bindataStaticImgsFavico() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/imgs/fav.ico"
	name := "static/imgs/fav.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsAppf12927113878f5ed9a9cjs reads file data from disk. It returns an error on failure.
func bindataStaticJsAppf12927113878f5ed9a9cjs() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/app.f12927113878f5ed9a9c.js"
	name := "static/js/app.f12927113878f5ed9a9c.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsAppf12927113878f5ed9a9cjsmap reads file data from disk. It returns an error on failure.
func bindataStaticJsAppf12927113878f5ed9a9cjsmap() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/app.f12927113878f5ed9a9c.js.map"
	name := "static/js/app.f12927113878f5ed9a9c.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsFlexiblejs reads file data from disk. It returns an error on failure.
func bindataStaticJsFlexiblejs() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/flexible.js"
	name := "static/js/flexible.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsManifest2ae2e69a05c33dfc65f8js reads file data from disk. It returns an error on failure.
func bindataStaticJsManifest2ae2e69a05c33dfc65f8js() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/manifest.2ae2e69a05c33dfc65f8.js"
	name := "static/js/manifest.2ae2e69a05c33dfc65f8.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsManifest2ae2e69a05c33dfc65f8jsmap reads file data from disk. It returns an error on failure.
func bindataStaticJsManifest2ae2e69a05c33dfc65f8jsmap() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/manifest.2ae2e69a05c33dfc65f8.js.map"
	name := "static/js/manifest.2ae2e69a05c33dfc65f8.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsTestjs reads file data from disk. It returns an error on failure.
func bindataStaticJsTestjs() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/test.js"
	name := "static/js/test.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsVendorce16a214c4761af53a7djs reads file data from disk. It returns an error on failure.
func bindataStaticJsVendorce16a214c4761af53a7djs() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/vendor.ce16a214c4761af53a7d.js"
	name := "static/js/vendor.ce16a214c4761af53a7d.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// bindataStaticJsVendorce16a214c4761af53a7djsmap reads file data from disk. It returns an error on failure.
func bindataStaticJsVendorce16a214c4761af53a7djsmap() (*asset, error) {
	path := "/Users/feynmanyuan/projects/blockchain/golang/riceis/src/bytemurmur.com/server/static/js/vendor.ce16a214c4761af53a7d.js.map"
	name := "static/js/vendor.ce16a214c4761af53a7d.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}


//
// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
//
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
// nolint: deadcode
//
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

//
// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or could not be loaded.
//
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, &os.PathError{Op: "open", Path: name, Err: os.ErrNotExist}
}

//
// AssetNames returns the names of the assets.
// nolint: deadcode
//
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

//
// _bindata is a table, holding each asset generator, mapped to its name.
//
var _bindata = map[string]func() (*asset, error){
	"static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css":     bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcss,
	"static/css/app.790e9ad3a938e1598034cdd790f5d2bd.css.map": bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcssmap,
	"static/dist/index.html":                                  bindataStaticDistIndexhtml,
	"static/fonts/element-icons.6f0a763.ttf":                  bindataStaticFontsElementicons6f0a763ttf,
	"static/imgs/avatar.jpg":                                  bindataStaticImgsAvatarjpg,
	"static/imgs/fav.ico":                                     bindataStaticImgsFavico,
	"static/js/app.f12927113878f5ed9a9c.js":                   bindataStaticJsAppf12927113878f5ed9a9cjs,
	"static/js/app.f12927113878f5ed9a9c.js.map":               bindataStaticJsAppf12927113878f5ed9a9cjsmap,
	"static/js/flexible.js":                                   bindataStaticJsFlexiblejs,
	"static/js/manifest.2ae2e69a05c33dfc65f8.js":              bindataStaticJsManifest2ae2e69a05c33dfc65f8js,
	"static/js/manifest.2ae2e69a05c33dfc65f8.js.map":          bindataStaticJsManifest2ae2e69a05c33dfc65f8jsmap,
	"static/js/test.js":                                       bindataStaticJsTestjs,
	"static/js/vendor.ce16a214c4761af53a7d.js":                bindataStaticJsVendorce16a214c4761af53a7djs,
	"static/js/vendor.ce16a214c4761af53a7d.js.map":            bindataStaticJsVendorce16a214c4761af53a7djsmap,
}

//
// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
//
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, &os.PathError{
					Op: "open",
					Path: name,
					Err: os.ErrNotExist,
				}
			}
		}
	}
	if node.Func != nil {
		return nil, &os.PathError{
			Op: "open",
			Path: name,
			Err: os.ErrNotExist,
		}
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}


type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{Func: nil, Children: map[string]*bintree{
	"static": {Func: nil, Children: map[string]*bintree{
		"css": {Func: nil, Children: map[string]*bintree{
			"app.790e9ad3a938e1598034cdd790f5d2bd.css": {Func: bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcss, Children: map[string]*bintree{}},
			"app.790e9ad3a938e1598034cdd790f5d2bd.css.map": {Func: bindataStaticCssApp790e9ad3a938e1598034cdd790f5d2bdcssmap, Children: map[string]*bintree{}},
		}},
		"dist": {Func: nil, Children: map[string]*bintree{
			"index.html": {Func: bindataStaticDistIndexhtml, Children: map[string]*bintree{}},
		}},
		"fonts": {Func: nil, Children: map[string]*bintree{
			"element-icons.6f0a763.ttf": {Func: bindataStaticFontsElementicons6f0a763ttf, Children: map[string]*bintree{}},
		}},
		"imgs": {Func: nil, Children: map[string]*bintree{
			"avatar.jpg": {Func: bindataStaticImgsAvatarjpg, Children: map[string]*bintree{}},
			"fav.ico": {Func: bindataStaticImgsFavico, Children: map[string]*bintree{}},
		}},
		"js": {Func: nil, Children: map[string]*bintree{
			"app.f12927113878f5ed9a9c.js": {Func: bindataStaticJsAppf12927113878f5ed9a9cjs, Children: map[string]*bintree{}},
			"app.f12927113878f5ed9a9c.js.map": {Func: bindataStaticJsAppf12927113878f5ed9a9cjsmap, Children: map[string]*bintree{}},
			"flexible.js": {Func: bindataStaticJsFlexiblejs, Children: map[string]*bintree{}},
			"manifest.2ae2e69a05c33dfc65f8.js": {Func: bindataStaticJsManifest2ae2e69a05c33dfc65f8js, Children: map[string]*bintree{}},
			"manifest.2ae2e69a05c33dfc65f8.js.map": {Func: bindataStaticJsManifest2ae2e69a05c33dfc65f8jsmap, Children: map[string]*bintree{}},
			"test.js": {Func: bindataStaticJsTestjs, Children: map[string]*bintree{}},
			"vendor.ce16a214c4761af53a7d.js": {Func: bindataStaticJsVendorce16a214c4761af53a7djs, Children: map[string]*bintree{}},
			"vendor.ce16a214c4761af53a7d.js.map": {Func: bindataStaticJsVendorce16a214c4761af53a7djsmap, Children: map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
